### ISSUE TITLE
K8s migration

### ISSUE THREAD

**Issue by l4b4r4b4b4** [N5GEH/n5geh.tutorials.entirety_step_by_step_deprecated#1]
Are there any plans to migrate this project to k8s?

**Comment by StWiemann** [comment]
Hi @l4b4r4b4b4,
I successfully deployed this to a K8s Cluster. However, since Entirety uses some config-files I had to use a persistent Volume, which I had access to. I used a NFS-volume for that. If you're happy with that little "trick" I could share my config with you.
Concerning a K8s native implementation of Entirety: I don't think that this is gonna happen any time soon.

**Comment by l4b4r4b4b4** [comment]
hi @StWiemann 
it would be awesome, to get a look on how you implemented it. Do you have a lot of experience with k8s?

**Comment by StWiemann** [comment]
Hi @l4b4r4b4b4 
"A lot of experience" would be a stretch, but I'm working with it on a regular basis.
Are you trying to deploy this to a real cluster or are you using some kind of local machine?
In case of a local machine please refer to this article first (if you don't already know about this) and make sure you understand the differences between "PersistentVolume" and "PersistenVolumeClaim" and how to use it in a Pod.
[Configure a Pod to Use a PersistentVolume for Storage](https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/)

If you are working with a hosted cluster you will need a persistent volume presented by a storage class of a specific storage provider. In this case I used a NFS-Storage as provider and created a corresponding storage class.
[Kubernetes Volumes: NFS](https://kubernetes.io/docs/concepts/storage/volumes/#nfs)


It is important to create the persistent volume first. Because you need to be able to access it and put your files there before you create the deployment :)

If you already knew all of this: I am sorry that I made you read through it again.

This is not exactly the deployment we use, but it should give you a good idea how to proceed with your implementation:

The Volume-Claim

```yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: entirety
  namespace: entirety
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100m
  storageClassName: nfs-client
  volumeMode: Filesystem
```

The Entirety-Deployment
Please note that the data structure on my NFS-Host is as follows:
`/path/to/NFS-Storage/persistentVolume/data/-all the entirety data-`

```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: entirety
  namespace: entirety
spec:
  replicas: 1
  selector:
    matchLabels:
      app: entirety
  template:
    metadata:
      labels:
        app: entirety
    spec:
      containers:
      - env:
        - name: CLIENT_SECRET
          value: /data/client_secrets.json
        - name: DEVICE_WIZARD_CONFIG
          value: /data/entirety.json
        image: n5geh/entirety:latest
        imagePullPolicy: IfNotPresent
        name: entirety
        ports:
        - containerPort: 80
          name: entirety-web
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: entirety-volume
          subPath: ./data
      restartPolicy: Always
      volumes:
      - name: entirety-volume
        persistentVolumeClaim:
          claimName: entirety
```

Please let me know whether this was helpful to you. Since I edited quite a lot of the yaml you might want to double check it. 
EDIT: Of course you will also need a service which fits your cluster-infrastructure to access entirety via browser :)
